# fly.toml app configuration file generated for macso-patient-dream-1724 on 2025-08-25T21:03:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'macso-patient-dream-1724'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
